Run containers as root
With userid/groupd seems not to work in GitHub Actions:

Error: Failed to launch the browser process!
chrome_crashpad_handler: --database is required
Try 'chrome_crashpad_handler --help' for more information.